### PR TITLE
Fix email template issues

### LINKED ISSUE #369: Fix bugs on the email template
**Describe the bug**
Some of the spacing is off, there are some broken links, and the year is also wrong.

**Expected behavior**
Fix the issues on the email template

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose

The purpose of this PR is to fix #369 

## Goals
Add the required word spacing, renew the old links, and change the year.

## Approach
Fix all the issues in the email template

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java [hunk 1]
```diff
@@ -126,16 +126,16 @@ public void sendMenteeSelectionEmails(long id, Optional<Program> program) throws
                     "It is with much pleasure we inform you that we have completed the first round of mentor-mentee matching.<br />" +
                     "There are a few points that we would like to share with you with regard to the mentee applications.<br />"+
                     "<ul>"+
```
Comment (anjula-sack) [inline src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java:128]: @gajindubandara Did you check the other templates for spacing issues as well?

Comment (gajindubandara) [reply src/main/java/org/sefglobal/scholarx/util/ProgramUtil.java:128]: No! I'll check the others as well.

**Review by anjula-sack — APPROVED** [review]
Thank you! @gajindubandara
